version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: match
      POSTGRES_USER: match
      POSTGRES_PASSWORD: match
    ports:
      - "5433:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:7222
    volumes:
      - ./server:/code
    ports:
      - "7222:7222"
    depends_on:
      - db
      - elasticsearch
  client:
    build:
      context: ./client
    ports:
      - '5222:5222'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: serve -s dist -l 5222

volumes:
  postgres_data:
  elasticsearch_data:
