export type TalentType = {
  id: number;
  name: string;
  profilePicture: string;
  expertise: string;
  experience: number; // years
  score: number; // out of 10
  description: string;
  email: string;
  website: string;
  twitter: string;
  linkedin: string;
  programmingLanguages: string[];
  frameworks?: string[];
  databaseManagement?: string[];
  versionControl?: string[];
};

export const TALENTS: TalentType[] = [
  {
    id: 1,
    name: "John Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Full Stack Developer",
    experience: 5,
    score: 7.5,
    description:
      "I am a full stack developer with 5 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test1@gmail.com",
    website: "https://www.test1.com",
    twitter: "https://www.twitter.com/test1",
    linkedin: "https://www.linkedin.com/test1",
    programmingLanguages: ["Javascript", "Python", "Java"],
    frameworks: ["React", "Angular", "Vue"],
    databaseManagement: ["MySQL", "MongoDB"],
    versionControl: ["Git", "SVN"],
  },
  {
    id: 2,
    name: "Afolabi Ibrahim",
    profilePicture:
      "https://avatars.githubusercontent.com/u/88886556?s=400&u=1a934e33ebe9bf2f5ed343697e17d236e2213850&v=4",
    expertise: "Frontend Developer",
    experience: 3,
    score: 8.2,
    description:
      "I am a frontend developer with 3 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test2@gmail.com",
    website: "https://www.test2.com",
    twitter: "https://www.twitter.com/test2",
    linkedin: "https://www.linkedin.com/test2",
    programmingLanguages: ["Javascript", "Typescript"],
    frameworks: ["React", "Angular"],
    versionControl: ["Git"],
  },
  {
    id: 3,
    name: "James Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Backend Developer",
    experience: 4,
    score: 6.8,
    description:
      "I am a backend developer with 4 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test3@gmail.com",
    website: "https://www.test3.com",
    twitter: "https://www.twitter.com/test3",
    linkedin: "https://www.linkedin.com/test3",
    programmingLanguages: ["Python", "Java"],
    frameworks: ["Django", "Spring"],
    databaseManagement: ["MySQL", "PostgreSQL"],
    versionControl: ["Git"],
  },
  {
    id: 4,
    name: "Fathiu Olayemi",
    profilePicture:
      "https://media.licdn.com/dms/image/D4D03AQEEiFIfQF4ZUQ/profile-displayphoto-shrink_800_800/0/1673228471628?e=1718236800&v=beta&t=cmjbbesPE8xledNUI2dPuAOR_AsEVLFgX2_v9jC-33k",
    expertise: "Brand Designer",
    experience: 6,
    score: 9.1,
    description:
      "I am a brand designer with 6 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test4@gmail.com",
    website: "https://www.test4.com",
    twitter: "https://www.twitter.com/test4",
    linkedin: "https://www.linkedin.com/test4",
    programmingLanguages: ["Python", "Shell"],
    frameworks: ["Ansible", "Terraform"],
    databaseManagement: ["MySQL", "PostgreSQL"],
    versionControl: ["Git"],
  },
  {
    id: 5,
    name: "Alex Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Mobile App Developer",
    experience: 2,
    score: 7.3,
    description:
      "I am a mobile app developer with 2 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test5@gmail.com",
    website: "https://www.test5.com",
    twitter: "https://www.twitter.com/test5",
    linkedin: "https://www.linkedin.com/test5",
    programmingLanguages: ["Swift", "Kotlin"],
    frameworks: ["React Native", "Flutter"],
    versionControl: ["Git"],
  },
  {
    id: 6,
    name: "Fawaz Shobogun",
    profilePicture:
      "https://media.licdn.com/dms/image/D4D03AQHFL6Kc_Hq0SA/profile-displayphoto-shrink_800_800/0/1684461474844?e=1718236800&v=beta&t=97EX65w826muAU0zhTMykE4iUiPOucbjZ3NPke4GMQ8",
    expertise: "UI/UX Designer",
    experience: 4,
    score: 9.4,
    description:
      "I am a UI/UX designer with 4 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test6@gmail.com",
    website: "https://www.test6.com",
    twitter: "https://www.twitter.com/test6",
    linkedin: "https://www.linkedin.com/test6",
    programmingLanguages: ["HTML", "CSS"],
    frameworks: ["React", "Vue"],
    versionControl: ["Git"],
  },
  {
    id: 7,
    name: "AbdulMalik Bello",
    profilePicture:
      "https://media.licdn.com/dms/image/C5603AQH7XFb4sECzVg/profile-displayphoto-shrink_800_800/0/1593295359584?e=1718236800&v=beta&t=s-fRAPl-HGfoMfn0aWnoPCCHMFMytiwROtwwWE251MM",
    expertise: "Data Scientist",
    experience: 5,
    score: 8.7,
    description:
      "I am a data scientist with 5 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test7@gmail.com",
    website: "https://www.test7.com",
    twitter: "https://www.twitter.com/test7",
    linkedin: "https://www.linkedin.com/test7",
    programmingLanguages: ["Python", "R"],
    frameworks: ["TensorFlow", "PyTorch"],
    databaseManagement: ["MySQL", "MongoDB"],
  },
  {
    id: 8,
    name: "Emily Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Frontend Developer",
    experience: 3,
    score: 7.9,
    description:
      "I am a frontend developer with 3 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test8@gmail.com",
    website: "https://www.test8.com",
    twitter: "https://www.twitter.com/test8",
    linkedin: "https://www.linkedin.com/test8",
    programmingLanguages: ["Javascript", "Typescript"],
    frameworks: ["React", "Angular"],
    versionControl: ["Git"],
  },
  {
    id: 9,
    name: "David Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Backend Developer",
    experience: 4,
    score: 6.5,
    description:
      "I am a backend developer with 4 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test9@gmail.com",
    website: "https://www.test9.com",
    twitter: "https://www.twitter.com/test9",
    linkedin: "https://www.linkedin.com/test9",
    programmingLanguages: ["Python", "Java"],
    frameworks: ["Django", "Spring"],
    databaseManagement: ["MySQL", "PostgreSQL"],
  },
  {
    id: 10,
    name: "Olivia Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Full Stack Developer",
    experience: 5,
    score: 8.3,
    description:
      "I am a full stack developer with 5 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test10@gmail.com",
    website: "https://www.test10.com",
    twitter: "https://www.twitter.com/test10",
    linkedin: "https://www.linkedin.com/test10",
    programmingLanguages: ["Javascript", "Python", "Java"],
    frameworks: ["React", "Angular", "Vue"],
    databaseManagement: ["MySQL", "MongoDB"],
    versionControl: ["Git", "SVN"],
  },
  {
    id: 11,
    name: "Sophia Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Frontend Developer",
    experience: 2,
    score: 7.6,
    description:
      "I am a frontend developer with 2 years of experience. I have worked on various web projects and have a strong understanding of HTML, CSS, and JavaScript.",
    email: "test11@gmail.com",
    website: "https://www.test11.com",
    twitter: "https://www.twitter.com/test11",
    linkedin: "https://www.linkedin.com/test11",
    programmingLanguages: ["HTML", "CSS", "JavaScript"],
    frameworks: ["React", "Vue"],
    versionControl: ["Git"],
  },
  {
    id: 12,
    name: "Liam Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Backend Developer",
    experience: 3,
    score: 8.7,
    description:
      "I am a backend developer with 3 years of experience. I have worked on various server-side projects and have a strong understanding of backend technologies like Node.js and databases like MongoDB.",
    email: "test12@gmail.com",
    website: "https://www.test12.com",
    twitter: "https://www.twitter.com/test12",
    linkedin: "https://www.linkedin.com/test12",
    programmingLanguages: ["JavaScript", "TypeScript"],
    frameworks: ["Express", "NestJS"],
    databaseManagement: ["MongoDB", "MySQL"],
    versionControl: ["Git"],
  },
  {
    id: 13,
    name: "Mia Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Mobile App Developer",
    experience: 4,
    score: 9.2,
    description:
      "I am a mobile app developer with 4 years of experience. I have worked on various mobile app projects and have a strong understanding of mobile development frameworks like React Native and Flutter.",
    email: "test13@gmail.com",
    website: "https://www.test13.com",
    twitter: "https://www.twitter.com/test13",
    linkedin: "https://www.linkedin.com/test13",
    programmingLanguages: ["JavaScript", "TypeScript"],
    frameworks: ["React Native", "Flutter"],
    versionControl: ["Git"],
  },
  {
    id: 14,
    name: "Noah Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Full Stack Developer",
    experience: 6,
    score: 9.8,
    description:
      "I am a full stack developer with 6 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test14@gmail.com",
    website: "https://www.test14.com",
    twitter: "https://www.twitter.com/test14",
    linkedin: "https://www.linkedin.com/test14",
    programmingLanguages: ["Javascript", "Python", "Java"],
    frameworks: ["React", "Angular", "Vue"],
    databaseManagement: ["MySQL", "MongoDB"],
    versionControl: ["Git", "SVN"],
  },
  {
    id: 15,
    name: "Emma Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Frontend Developer",
    experience: 4,
    score: 8.5,
    description:
      "I am a frontend developer with 4 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test15@gmail.com",
    website: "https://www.test15.com",
    twitter: "https://www.twitter.com/test15",
    linkedin: "https://www.linkedin.com/test15",
    programmingLanguages: ["Javascript", "Typescript"],
    frameworks: ["React", "Angular"],
    versionControl: ["Git"],
  },
  {
    id: 16,
    name: "Liam Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Backend Developer",
    experience: 5,
    score: 7.9,
    description:
      "I am a backend developer with 5 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test16@gmail.com",
    website: "https://www.test16.com",
    twitter: "https://www.twitter.com/test16",
    linkedin: "https://www.linkedin.com/test16",
    programmingLanguages: ["Python", "Java"],
    frameworks: ["Django", "Spring"],
    databaseManagement: ["MySQL", "PostgreSQL"],
    versionControl: ["Git"],
  },
  {
    id: 17,
    name: "Olivia Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "DevOps Engineer",
    experience: 7,
    score: 9.5,
    description:
      "I am a DevOps engineer with 7 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test17@gmail.com",
    website: "https://www.test17.com",
    twitter: "https://www.twitter.com/test17",
    linkedin: "https://www.linkedin.com/test17",
    programmingLanguages: ["Python", "Shell"],
    frameworks: ["Ansible", "Terraform"],
    databaseManagement: ["MySQL", "PostgreSQL"],
    versionControl: ["Git"],
  },
  {
    id: 18,
    name: "Sophia Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Mobile App Developer",
    experience: 3,
    score: 8.2,
    description:
      "I am a mobile app developer with 3 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test18@gmail.com",
    website: "https://www.test18.com",
    twitter: "https://www.twitter.com/test18",
    linkedin: "https://www.linkedin.com/test18",
    programmingLanguages: ["Swift", "Kotlin"],
    frameworks: ["React Native", "Flutter"],
    versionControl: ["Git"],
  },
  {
    id: 19,
    name: "Ava Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "UI/UX Designer",
    experience: 5,
    score: 9.7,
    description:
      "I am a UI/UX designer with 5 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test19@gmail.com",
    website: "https://www.test19.com",
    twitter: "https://www.twitter.com/test19",
    linkedin: "https://www.linkedin.com/test19",
    programmingLanguages: ["HTML", "CSS"],
    frameworks: ["React", "Vue"],
    versionControl: ["Git"],
  },
  {
    id: 20,
    name: "Isabella Doe",
    profilePicture: "https://100k-faces.glitch.me/random-image",
    expertise: "Data Scientist",
    experience: 6,
    score: 8.9,
    description:
      "I am a data scientist with 6 years of experience. I have worked on a number of projects and have a good understanding of the tech stack.",
    email: "test20@gmail.com",
    website: "https://www.test20.com",
    twitter: "https://www.twitter.com/test20",
    linkedin: "https://www.linkedin.com/test20",
    programmingLanguages: ["Python", "R"],
    frameworks: ["TensorFlow", "PyTorch"],
    databaseManagement: ["MySQL", "MongoDB"],
  },
];
