name: Deployment action
run-name: ${{ github.actor }} is deploying using  GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  build_and_push_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Client Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: Dockerfile
          push: true
          tags: hayadev/client:latest

      - name: Build and push Server Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: Dockerfile
          push: true
          tags: hayadev/server:latest

  deploy_client_to_render:
    runs-on: ubuntu-latest
    needs: build_and_push_client
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_CLIENT_WEBHOOK_URL }}

  deploy_server_to_render:
      runs-on: ubuntu-latest
      needs: build_and_push_client
      steps:
        - name: Deploy server to Render
          run: |
            curl -X POST ${{ secrets.RENDER_SERVER_WEBHOOK_URL }}
      

